[env:esp32-s3-devkitm-1]
lib_extra_dirs = ../lib
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

upload_port = COM5

monitor_port = COM5
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -DCORE_DEBUG_LEVEL=5
    -DLOG_LOCAL_LEVEL=ESP_LOG_VERBOSE