#include "../../../lib/robot-common/src/task/task.c"
#include "../../../lib/robot-common/src/task/task_protocol.c"
#include "../../src/task/task_coordinator.c"
#include "../../../esp32-arm/src/task/arm_manager.c"
#include "../../../esp32-arm/src/communication/task_server.c"
